import Topbar from '../components/Topbar';
import BackButton from '../components/BackButton';
import Card from '../components/Card';
import { useTheme } from '../context/ThemeContext';
import { briefingSections, project } from '../data/mockData';

export default function Briefing() {
  const { isDark, toggleDark } = useTheme();

  return (
    <div>
      <Topbar
        title={isDark ? 'Evening Wrap-up' : 'Morning Briefing'}
        subtitle={`${project.dateLabel} · Generated by Cerebro`}
        actions={
          <>
            <BackButton />
            <button className="btn-primary" onClick={toggleDark}>
              {isDark ? '☀️ Switch to morning' : '🌙 Switch to evening'}
            </button>
          </>
        }
      />
      <div className="briefing-mode">
        {briefingSections.map((section, i) => (
          <div
            className="briefing-section"
            key={section.label}
            style={i === briefingSections.length - 1 ? { marginBottom: 0 } : undefined}
          >
            <div className="bs-label" style={{ color: section.labelColor }}>
              {section.label}
            </div>
            <div className="bs-items">
              {section.items.map((item, j) => (
                <div className="bs-item" style={{ background: item.bg, borderRadius: 10 }} key={j}>
                  <div className="bs-dot" style={{ background: item.dotColor }} />
                  <div className="bs-text" dangerouslySetInnerHTML={{ __html: item.text }} />
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
      <Card style={{ background: 'var(--blue-light)', borderColor: 'rgba(37,99,235,.2)' }}>
        <div className="card-title" style={{ color: 'var(--blue)' }}>🧠 Cerebro recommendation</div>
        <div style={{ fontSize: 13, color: 'var(--text2)', lineHeight: 1.7 }}>
          Your single most important action today:{' '}
          <strong style={{ color: 'var(--text)' }}>
            make the Zone C crew decision and send the MEP fixture order.
          </strong>{' '}
          These two things, if delayed another day, create compounding risk that will be very difficult to recover
          from by Jun 10.
        </div>
      </Card>
    </div>
  );
}
